name: Pages
on:
  workflow_dispatch:

jobs:
  update-directory:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: setup node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: latest

      - name: generate
        run: |
          node .github/bin/generate-gh-pages.mjs

      - name: save
        run: |
          # Git config
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --allow-empty -m "Generate pages"
          git push --set-upstream origin main
